apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab16-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/lab16-static-pv
  storageClassName: manual
