apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  namespace: lab16-storage
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: static-pvc
